### ISSUE TITLE
Does Structor have bad UI ?

### ISSUE THREAD

**Issue by ipselon** [ipselon/structor#23]
I'm not UI/UX specialist. So, it would be extremely helpful to know what is wrong with Structor's UI.

**Comment by brysgo** [comment]
@ipselon - Typically a UX should hide more complex functionality and default to the most common case. 

For example, I would look at all the places where there are large groups of buttons for doing something. (i.e. before | first | replace | wrap | last | after) and make it one button to insert a component.

Then maybe an arrow next to the insert button to drop down options of where to put the component. But if the user doesn't pick where the component goes, just put it below the selected component.

**Comment by ipselon** [comment]
As for me, it makes sense. I was afraid that many users don't want to click on the dropdown and then to choose an action. But now there are shortcuts, which simplify all actions. Thank you, probably I'll make it in the next release.

**Comment by brysgo** [comment]
No problem, I think structor is great. I'm planning on teaching a bunch of kids programming and I want them to get a chance to build something substantial and have the opportunity to play around in the code.

With the current state of react tooling, this would be impossible, but if we get structor generating a working website, I think they could have a lot of fun with it.

**Comment by ipselon** [comment]
Thank you for kind words. I really appreciate this. If you have any questions, please write directly in our Facebook group or on Dicsord channel. 
BTW, bootstrap-prepack is ready for website creation, there are all what you need - Express.js, Webpack build configs. And after you export project from Structor and build code you'll have working web site. Please watch video tutorials, and just try to follow all steps there.

**Comment by psimyn** [comment]
The UI is very good once you get used to heavy clipboard use. There was a slight learning curve for where/how to do things though. Here are some small things I've found confusing as a new user:


## Disabled states 
- When in view mode, the Hierarchy/Quick Options buttons don't do anything. Takes a minute to figure out you need to go back to edit mode first
- When loading spinner up, nothing is clickable. Possibly overlay whole screen to show this more clearly

## Selected Items
- Clicking twice on an element does different things (selects, then opens Component view)
This is convenient when I need it (to access props/code). But more commonly I am trying to select the Child after clicking a parent, which triggers the parent popup.
- Clicking outside of an element (in empty space) doesn't deselect it. Though given most space has elements or Action Panels, this is probably not an issue

## Hierarchy view
- Can't multi-select, so wrapping means wrapping first element then copying others. If there is an easier way to do this that'd be good (or allow drag/drop here)
Also since paste pastes AFTER selected element, not an easy way to paste inside (there is probably shortcut for this)
- After generating a component, you can no longer select children. For example if you make List component, then want to change ListItem from within Structor


## Breadcrumbs
- After clicking parent, could keep previously selected children visible (but greyed out). Jumping between grandparents/grandchildren takes a lot of clicks currently
- Highlighting selected element in Preview panel when mousing over breadcrumb would be useful


## Other
- Duplicated elements. For example when element is selected, you have the same buttons just over the element, and at the top. I've never been very into the clipboard buttons, since there are very common keyboard shortcuts for cut/copy/paste/delete
Hiding the replace/wrap/after things behind a menu will probably help a lot, there are a lot of things to scan at the moment (I usually just use wrap/replace/first)
- The "Item in clipboard" is sometimes not clear enough - particularly since it completely changes what all the buttons do. If I am just looking between Close and Cancel, the following two states do very different things:

![screen shot 2015-12-31 at 19 08 23](https://cloud.githubusercontent.com/assets/1731922/12062509/01ae565c-aff2-11e5-8c76-f224514fac8b.png)
![screen shot 2015-12-31 at 19 08 32](https://cloud.githubusercontent.com/assets/1731922/12062510/01b0269e-aff2-11e5-9b51-499356c8452e.png)


I'll update/add as I think of more, will maybe add separate section for server/backend stuff. Most of these are non-issues, but were things I noticed at some point.

**Comment by ipselon** [comment]
Thanks a lot for such a precise feedback. I will take in account all items in the list, and I'll answer step by step each issue, because there are some which are not really doable.

**Comment by auvipy** [comment]
why are they not doable? just curious to know :)

**Comment by ipselon** [comment]
@auvipy for example this one:

> After generating a component, you can no longer select children. For example if you make List     component, then want to change ListItem from within Structor

Structor can compose components on the page, then can generate the source code of new component taking selected component as the root for new one. But Structor can not change the source code of the component itself.

**Comment by auvipy** [comment]
I don't think that's necessary :)

**Comment by ipselon** [comment]
@psimyn  just released new version, and many proposals were taken in account. If you will have a chance take a look at new UI of Structor.

**Comment by psimyn** [comment]
thanks, looks great! I'll give it a try

**Comment by jdarling** [comment]
So after a 5 minute play session I would describe Structor as a cute toy.  Could be very useful but it has a long way to go.  As much as I HATE pop overs, I would suggest some getting started tips that popup and guide the user through 1st time usage.  Allow them to skip past or return to the tutorial at any time.

Figure out what exactly actions should do, clicking selects if you are in select mode (and setup mode buttons), double click to edit, bla bla bla.  Document it, and then follow it, always, at all times, no matter what.  A single user action should always perform the same action, not change once you have done something else.

A component pallet, for the love of jebus please add some type of component palette.  Or at least have the drop down pre-populate with all components grouped by functionality.  I thought something was broke till I accidentally mashed a key on my keyboard, then realized I had to type something to get something.  I would suggest looking at old Borland IDE's, IMHO they got it right, then everyone else followed their lead (actually I know everyone else followed their lead).

Quick keys and assignable shortcuts.  Maybe some presets, import/export of presets is a gold mine.

Also allow color choices, no matter what colors you pick you will have someone who has issues with them.  Some of us are color blind ;)  Rule of 3 maybe (identify actionable items with at lease 3 distinct visual differences, iconogrophy, text, color, font-weight, size, etc... pick 3 and keep to them)

As an example: red, BOLD, with a trash can icon means delete forever.

Users don't have to start the backend to edit their projects, so why does the documentation allude that you have to?

If you have the backend running then use something like HMR to do auto reloads.  Right now I can't figure out how to get my changes to display in the project without restarting the backend server.  Kinda sucks actually.

Some ideas on mouse+keyboard quick commands:
Drag and drop from some type of palette with CTRL/Command+Click to place multiple.
Shift+Drag to resize.
Shift+Drag in empty space to pan.
Mouse wheel to zoom.
Ctrl/Command mouse wheel to scroll vert.
Shift mouse wheel to scroll horz.

Everything you can do with a mouse you should be able to do with the keyboard, not necessarily should you be able to do everything (directly) with a mouse that you can do with a keyboard.  Everything should be available via a menu of some type.

I always loved the way AutoCAD had a command window where you could just type shit in and it worked like magic.  Also for every action performed it added it to the command history so you could easily "learn" how to command your way through anything.

Realistic preview.  Allow the user to specify the style sheets directly that their project uses.  Use those style sheets for the build/preview.

Overall this is a great idea for a project and something I have been looking for for a while now.  Glad to have stumbled upon it and looking forward to where it goes.  Sorry if any of the above is crass, its just my honest opinion.

Over everything else:

&lt;SteveBallmer voice="developers"&gt;
Consistency, Consistency, Consistency, Consistency, 
Consistency, Consistency, Consistency, Consistency, 
Consistency, Consistency, Consistency, Consistency, 
Consistency, Consistency, Consistency, Consistency
&lt;/SteveBallmer&gt;

**Comment by ipselon** [comment]
@jdarling, @psimyn, it would be great to have a new review of UI after so many releases. If you have a chance take a look at the last version. Also, I wrote some docs... Thanks.

**Comment by tx4x** [comment]
after building some similar tools i am also surprised there isn't any standard functionality as 
- drag components from a palette 
- move items around with the mouse
- real code editor (dual view)

is this something planned ? I am asking because I'm looking for a new starting project to roll out me new IDE (http://pearls-media.com/control-freak/screenshots/) and I'd love to build on structor but it seems rather difficult to due different design goals.
thanks, 
g
