### ISSUE TITLE
Question about CSS and (other) JS  libs.

### ISSUE THREAD

**Issue by theanthonyplan** [ipselon/structor#41]
A quick foreword: I wanted to congratulate you on producing some outstanding software.  I came across the project when it was react-ui-builder. The progress that's been made since then is tremendous.  I just wanted to thank you on behalf of the community for all of your kickass efforts. We owe you some beer.

And now for the question:
Is there a way to link in an existing .css file to be used by the live editor?  Additionally, if I'm trying to use some third-party .js library, do I want to link that through the "Script (analytics, etc.)" tab of the page component modal?

Not worried about cases where the project is deployed since I'm using Django.  But as far as the live editor goes, I have no idea how I should be trying to handle static media (aside from adding style props to the components).

Thanks again.

Update 0:
I just remembered that html --> jsx converters exist.  I need to take a better look at what that process would entail, but it may be a serviceable workaround if nothing else.

Update 1: 
In the meantime I will be revisiting the concepts detailed by https://github.com/christianalfoni/react-webpack-cookbook/wiki/Loading-CSS 

Until someone can point me in a new direction I will attempt to move forward based on the patterns they described. Not sure if any of it applies to structor's operation, but its a good starting place for anyone else who might be confused about how .css fits into the mix.

**Comment by ipselon** [comment]
@theanthonyplan thank you for your kind words, I appreciate this very much. I'm sorry for late response.

All the existing projects for Structor have third-party resources like .CSS, .JS, fonts, and other in `src/client/assets` directory. As far as the builder uses webpack for compiling all sources (along with static ones), we have to drop the line about any new resource into webpack endpoint. There is a file which is such an endpoint for webpack: `.structor/src/index.js`.

So, to include some .CSS file you have to copy it into `src/client/assets` (or somewhere within the project folder) and just add a line `require('<relative path to file>')` into `.structor/src/index.js` file.

Additionaly you have to add `require(<relative path to file>)` into `src/client/main.js` for webpack which is building your project manually by running `npm run build-client` (different proejcts have different run commands, look at `package.json` scripts field).

There is a video about how to add jQuery plugin into project: https://www.youtube.com/watch?v=_TKmFDLGFdQ, this video was made for React UI Builder, but the principles are the same as for Structor's project, except metatada folder name has to be `.structor` instead of `.buidler`.

**Comment by theanthonyplan** [comment]
>So, to include some .CSS file you have to copy it into src/client/assets (or somewhere within the project folder) and just add a line require('<relative path to file>') into .structor/src/index.js file.

Wow! That's exactly the piece of info I was seeking, thanks for your help.  Once I get my example system up and running I'll be sure to write up an example/docs for future reference.
