### ISSUE TITLE
why generator is removed from the latest version?

### ISSUE THREAD

**Issue by kadinwu** [ipselon/structor#57]
hi,
i was using the previous version in structor, there is one very pretty function - react/redux generator. but in latest version, cannot see them. any purpose why you remove them?
Thanks for your great work!

**Comment by ipselon** [comment]
the reason to remove offline generators because we want to create something like asset store for generators. And now you can use online generators, which do pretty the same as it was done by previous generators. 

Find generic generators when you try to create `New component` in the top toolbar.

Also, you may read a draft of my article about new Structor here: https://github.com/ipselon/structor/wiki/New-page

**Comment by kadinwu** [comment]
I see, thanks for your quick reply.
moving forward to new structor, thanks for your work.
