### ISSUE TITLE
Project roadmap & status

### ISSUE THREAD

**Issue by blntylmn** [ipselon/structor#67]
Good job. I play around with it and i really like.. I saw on twitter that you said you merged react-boilerplate 2 months ago.. So what is the current status ? Is this project still alive and will be there a new release soon ?

**Comment by ipselon** [comment]
@blntylmn Thanks for your appreciation. And yes, I'm working on integrating Structor with react-bolierplate, and many things will change. I guess the next release will be in a month or less. Thanks for asking, I'll do my best to make it quick...

**Comment by blntylmn** [comment]
Hi, you updated repo yesterday and I tried. But it seems to use old folder structure not react-boilerplate. Starter projects also old and there is no new starter project with react-boilerplate. Is it true or did I something wrong ?..

**Comment by ipselon** [comment]
@blntylmn Hi, the recent update is only a preparation for the next release. I had to update the source code in master branch, sorry. It uses the same structure of the Structor meta folder, but there are some changes in webpack configuration, and in component index file. This is not obvious from that code. As a seed project for the next release will be the fork of `react-boilerplate` (not prepared so far) with predefined meta folder configuration. Also, now I'm porting exiting generators from other projects and I'm improving usability regarding copy&paste flow (it should be simpler). It is left not much time to the release. I much appreciate your attitude.

**Comment by blntylmn** [comment]
@ipselon Hi, as you mentioned you will use `react-boilerplate` as a seed project in next release. So if I use now `react-boilerplate` now for my next project can I integrate it to structor as a seed later or do I have to start over?  I mean will be easy to integrating existing projects to new structor ?

**Comment by ipselon** [comment]
@blntylmn Sorry for delay. Yup, you will be able to install Structor right into your project locally, and easily integrate all your components into Structor's library. The only requirement is to use structure of components files which is proposed by react-boilerplate. Thanks.

**Comment by ipselon** [comment]
Hi @blntylmn. New version adopted for React Boilerplate is available: https://github.com/ipselon/react-boilerplate

You just may clone/download a fork of React Boilerplate repo and setup it as it is said in the instruction there.

**Comment by ipselon** [comment]
The next steps:

1. A generators publishing feature.
1. Migration of (not all) existing generators into React Boilerplate project on the market.

**Comment by theanthonyplan** [comment]
Saw the changes to the project code and just got a few builds running, this is absolutely great work @ipselon.  Thanks again for all of your efforts.

It looks like I can still use the previous version to access/update my old generators, that is a relief!  I am in the process of reformatting all of my old generators, I wanted to ask you if there are any major changes planned for how/which files get created for new generators.  With the previous version it seems like the only way to make a generator that has an api.js file, would be to fork a project that already had one included in its own structure.  

I thought I saw you mention somewhere that there was a file or component manager planned, I was unsure if that meant it would manage the files of newly generated files or if it was a manager for the local redux files(like the project component index, or store.js) and the files for any installed components.

Thanks again for your help.

avg

**Comment by blntylmn** [comment]
Thank you for update.. I will try asap and give you more feedback... Nice work btw.

**Comment by OlegMalkov** [comment]
@ipselon Did you see this framework https://github.com/salsita/redux-elm ?
Looks like it's better approach to structure project code than https://github.com/mxstbr/react-boilerplate

**Comment by ipselon** [comment]
#### In the next release of Structor

We are going to get rid of the marketplace as it is, consequently we'll get rid of the registration process to obtain the access to the components generation.

But it does not mean that we will remove the gallery of pre-created components. This is just a new way to have components installed into the application structure.

We are intend to create a new mechanizm for installing the components - install components from packages. The component package is an archive with special structure. The source code of the package should be located on the GH. In order to see the package description in the Structor's gallery the address of the GH repo should be included into a separate GH repo which will serve as a marketplace index for Structor.

When the user selects some package in the Structor's gallery he will be prompted to select the components included into the package he wants to install.

Also, the user will have the ability to create own components package repo. As far as the package has a rather complex structure, Structor will have the ability to create and publish the repository package structure automatically from any group of the components in the Stuctor's library. The package's structure will include all needed files for each component generator in the group of components which the user wants to published on GH.

Applying such an approach in components installation into Structor library (along with application structure) we will achieve several advantages:
* Remove the account registration and authentication
* Give the ability to develop React components packages which may be related with each other
* Give the ability to develop the source code of the component generators in a way the developers used on GH.
* Give the ability to create a rich documentation for the entire package right on the GH.

**Comment by ipselon** [comment]
All features I've mentioned before are implemented in Structor versions > 2.2.x
